//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurneroFaeracWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int AppointmentId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Details { get; set; }
    
        public virtual DoctorDetails DoctorDetails { get; set; }
        public virtual PatientDetails PatientDetails { get; set; }
    }
}
