//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurneroFaeracWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctores()
        {
            this.DiasTrabajoDoc = new HashSet<DiasTrabajoDoc>();
            this.IndiceHorarios = new HashSet<IndiceHorarios>();
            this.ProgramaDoc = new HashSet<ProgramaDoc>();
            this.TablaTurnos = new HashSet<TablaTurnos>();
            this.Turnos = new HashSet<Turnos>();
            this.TurnosMod = new HashSet<TurnosMod>();
        }
    
        public int IdDoc { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> idConsultorio { get; set; }
        public string NombreDoc { get; set; }
        public string ApeDoc { get; set; }
        public Nullable<int> IDEspecializacion { get; set; }
        public Nullable<int> Flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiasTrabajoDoc> DiasTrabajoDoc { get; set; }
        public virtual Especializaciones Especializaciones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndiceHorarios> IndiceHorarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramaDoc> ProgramaDoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TablaTurnos> TablaTurnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turnos> Turnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurnosMod> TurnosMod { get; set; }
    }
}
