//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurneroFaeracWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndiceAnalisis
    {
        public int IdAnalisis { get; set; }
        public int IdPaciente { get; set; }
        public string LinkAnalisis { get; set; }
        public System.DateTime FechaAnalisis { get; set; }
    }
}
