//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurneroFaeracWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndiceHorarios
    {
        public int IdHorarioDoc { get; set; }
        public int IdDoc { get; set; }
        public string Apellido { get; set; }
        public Nullable<System.TimeSpan> DesdeTiempo { get; set; }
        public Nullable<System.TimeSpan> HastaTiempo { get; set; }
        public bool Activo { get; set; }
    
        public virtual Doctores Doctores { get; set; }
    }
}
