//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurneroFaeracWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TurneroNewEntities : DbContext
    {
        public TurneroNewEntities()
            : base("name=TurneroNewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointments> Appointments { get; set; }
        public virtual DbSet<Boxes> Boxes { get; set; }
        public virtual DbSet<Consultorios> Consultorios { get; set; }
        public virtual DbSet<DiasSemana> DiasSemana { get; set; }
        public virtual DbSet<DiasTrabajoDoc> DiasTrabajoDoc { get; set; }
        public virtual DbSet<DoctorDetails> DoctorDetails { get; set; }
        public virtual DbSet<Doctores> Doctores { get; set; }
        public virtual DbSet<Especializaciones> Especializaciones { get; set; }
        public virtual DbSet<HorariosDisponibles> HorariosDisponibles { get; set; }
        public virtual DbSet<HorariosPredefinidos> HorariosPredefinidos { get; set; }
        public virtual DbSet<IndiceAnalisis> IndiceAnalisis { get; set; }
        public virtual DbSet<IndiceGenero> IndiceGenero { get; set; }
        public virtual DbSet<IndiceHorarios> IndiceHorarios { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<PatientDetails> PatientDetails { get; set; }
        public virtual DbSet<ProgramaDoc> ProgramaDoc { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TablaHorarios> TablaHorarios { get; set; }
        public virtual DbSet<TablaTurnos> TablaTurnos { get; set; }
        public virtual DbSet<TipoUsuarios> TipoUsuarios { get; set; }
        public virtual DbSet<TurnoBox> TurnoBox { get; set; }
        public virtual DbSet<Turnos> Turnos { get; set; }
        public virtual DbSet<TurnosMod> TurnosMod { get; set; }
        public virtual DbSet<UserIntegrada> UserIntegrada { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Appointment> Appointment { get; set; }
    }
}
