//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurneroFaeracWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacientes()
        {
            this.HorariosDisponibles = new HashSet<HorariosDisponibles>();
            this.Turnos = new HashSet<Turnos>();
        }
    
        public int IdPaciente { get; set; }
        public string NombrePac { get; set; }
        public string ApePac { get; set; }
        public string DNIPac { get; set; }
        public Nullable<int> EdadPac { get; set; }
        public string GeneroPac { get; set; }
        public string TipoDNI { get; set; }
        public int IdUser { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Genero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorariosDisponibles> HorariosDisponibles { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turnos> Turnos { get; set; }
    }
}
