//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurneroFaeracWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramaDoc
    {
        public int IdPrograma { get; set; }
        public int IdDoc { get; set; }
        public int DiaSemana { get; set; }
        public Nullable<System.TimeSpan> Inicio { get; set; }
        public Nullable<System.TimeSpan> Fin { get; set; }
        public string NombrePac { get; set; }
        public Nullable<int> EdadPac { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Doctores Doctores { get; set; }
    }
}
