//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurneroFaeracWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaTurnos
    {
        public int IdTurno { get; set; }
        public int IdPaciente { get; set; }
        public Nullable<System.DateTime> Fin { get; set; }
        public Nullable<System.DateTime> inicio { get; set; }
        public string Estado { get; set; }
        public string NombrePaciente { get; set; }
        public string NombreDoc { get; set; }
        public string ApeDoc { get; set; }
        public Nullable<int> IdDia { get; set; }
        public string NombreDia { get; set; }
        public string Fecha { get; set; }
        public Nullable<int> EdadPac { get; set; }
        public Nullable<int> IdDoc { get; set; }
    
        public virtual Doctores Doctores { get; set; }
    }
}
