//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurneroFaeracWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turnos
    {
        public int IdTurno { get; set; }
        public int IdPaciente { get; set; }
        public int IdDoc { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<bool> TurnoRealizado { get; set; }
        public string ComentarioDoctor { get; set; }
    
        public virtual Doctores Doctores { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
